---
- name: Check if system is debian based
  ansible.builtin.assert:
    that:
      - ansible_os_family == 'Debian'
    fail_msg: "System must be debian based"
  ignore_errors: false

- name: Check if group exists
  ansible.builtin.assert:
    that:
      - kubernetes_ansible_inventory_group in groups
    fail_msg: "Group {{ kubernetes_ansible_inventory_group }} does not exists"
  ignore_errors: false

- name: Check if host is in group
  ansible.builtin.assert:
    that:
      - inventory_hostname in groups[kubernetes_ansible_inventory_group]
    fail_msg: "Host must be in group {{ kubernetes_ansible_inventory_group }}"
  ignore_errors: false

- name: Check if multiple control planes exists
  when:
    - inventory_hostname in groups['k8s-master']
    - groups['k8s-master'] | length > 1
  ansible.builtin.assert:
    that:
      - kubernetes_cluster_config.controlPlaneEndpoint is defined
      - kubernetes_cluster_config.controlPlaneEndpoint != ''
    fail_msg: "loadbalancer in kubernetes_cluster_config.controlPlaneEndpoint must be defined"
  ignore_errors: false
  any_errors_fatal: true

- name: Check if only 2 control planes exists
  when:
    - inventory_hostname in groups['k8s-master']
    - groups['k8s-master'] | length > 1
  ansible.builtin.assert:
    that:
      - groups['k8s-master'] | length > 2
    fail_msg: "at least 3 or more control planes are required"
  ignore_errors: false
  any_errors_fatal: true
