---
- name: Check kubernetes admin.conf
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_admin_conf_stat

- name: Setup control plane
  when: not kubernetes_admin_conf_stat.stat.exists
  block:
    - name: Initialize kubeadm
      ansible.builtin.command:
        cmd: >
          kubeadm init
          --config="{{ kubernetes_kubeadm_config_file_path }}"
          --ignore-preflight-errors="{{ kubernetes_ignore_preflight_errors }}"
        creates: /etc/kubernetes/admin.conf

    - name: Ensure .kube directory exists
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: "0755"

    - name: Create link of kubectl admin.conf to ~/.kube/conf
      ansible.builtin.file:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        state: link
        mode: "0644"
