---
- name: Check kubernetes admin.conf
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_admin_conf_stat

- name: Setup main control plane
  when:
    - inventory_hostname == groups['k8s-master'][0]
    - not kubernetes_admin_conf_stat.stat.exists
  block:
    - name: Add custom kubelet arguments
      ansible.builtin.template:
        src: kubeadm-conf.j2
        dest: "{{ kubernetes_kubeadm_config_file_path }}"
        mode: "0644"
      notify: Restart kubelet

    - name: Initialize kubeadm
      ansible.builtin.command:
        cmd: >
          kubeadm init
          --config="{{ kubernetes_kubeadm_config_file_path }}"
          --ignore-preflight-errors="{{ kubernetes_ignore_preflight_errors }}"
        creates: /etc/kubernetes/admin.conf

    - name: Ensure .kube directory exists
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: "0755"

    - name: Create link of kubectl admin.conf to ~/.kube/conf
      ansible.builtin.file:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        state: link
        mode: "0644"

    - name: Configure network
      ansible.builtin.command:
        cmd: "kubectl apply -f {{ kubernetes_network_config_file_path }}"
      until: kubernetes_apply_config_result is not failed
      retries: 10
      delay: 10
      register: kubernetes_apply_config_result
      changed_when: "'created' in kubernetes_apply_config_result.stdout"

- name: Get control plane join command
  when:
    - inventory_hostname == groups['k8s-master'][0]
  block:
    - name: Retrieve the certificate key
      ansible.builtin.command:
        cmd: kubeadm init phase upload-certs --upload-certs
      register: cert_key_output
      changed_when: false

    - name: Parse the certificate key
      ansible.builtin.set_fact:
        certificate_key: "{{ cert_key_output.stdout_lines[-1] }}"

    - name: Generate the control plane join command
      ansible.builtin.command:
        cmd: kubeadm token create --print-join-command --certificate-key {{ certificate_key }}
      register: control_plane_join_command
      changed_when: false

    - name: Display the control plane join command
      ansible.builtin.debug:
        verbosity: 2
        msg: "{{ control_plane_join_command.stdout }}"

    - name: Set control plane join command
      ansible.builtin.set_fact:
        control_plane_join_command: "{{ control_plane_join_command.stdout }}"

- name: Set control plane join command to all control planes
  ansible.builtin.set_fact:
    control_plane_join_command: "{{ hostvars[groups['k8s-master'][0]].control_plane_join_command }}"

- name: Setup other control planes
  when:
    - not kubernetes_admin_conf_stat.stat.exists
    - inventory_hostname != groups['k8s-master'][0]
  throttle: 1
  block:
    - name: Join control plane
      ansible.builtin.command:
        cmd: "{{ control_plane_join_command }}"
        creates: /etc/kubernetes/admin.conf
      until: "'This node has joined' in join_command_out.stdout"
      register: join_command_out

    - name: Ensure .kube directory exists
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: "0755"

    - name: Create link of kubectl admin.conf to ~/.kube/conf
      ansible.builtin.file:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        state: link
        mode: "0644"
