---
- name: Import checks
  ansible.builtin.include_tasks: check.yml

- name: Import vars
  ansible.builtin.include_vars: debian.yml
  when: ansible_os_family == 'Debian'

- name: Setup sysctl
  ansible.builtin.import_tasks: sysctl.yml

- name: Install kubernetes
  ansible.builtin.import_tasks: install.yml

- name: Setup control plane
  when: kubernetes_is_control_plane
  block:
    - name: Setup control plane
      ansible.builtin.import_tasks: control_plane.yml

    - name: Get worker node join command
      ansible.builtin.command:
        cmd: kubeadm token create --print-join-command
      register: kubernetes_kubeadm_join_command_result
      changed_when: false

- name: Set worker node join command
  ansible.builtin.set_fact:
    kubernetes_join_command: >
      {{ kubernetes_kubeadm_join_command_result.stdout }}
  when: kubernetes_kubeadm_join_command_result.stdout is defined
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups[kubernetes_ansible_inventory_group] }}"

- name: Debug print worker node join command
  ansible.builtin.debug:
    msg: "{{ kubernetes_join_command }}"
    verbosity: 2
  when: kubernetes_join_command is defined

- name: Setup nodes
  ansible.builtin.import_tasks: nodes.yml
  when:
    - not kubernetes_is_control_plane
    - kubernetes_join_command is defined
