---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: debian12-k8s-master-01
    box: debian/bookworm64
    groups:
      - kubernetes
    provider_options:
      memory: 2048
      cpus: 2

  - name: debian12-k8s-worker-01
    box: debian/bookworm64
    groups:
        - kubernetes
    provider_options:
      memory: 2048
      cpus: 2

provisioner:
  name: ansible
  inventory:
    host_vars:
      debian12-k8s-worker-01:
        kubernetes_is_control_plane: false

      debian12-k8s-master-10:
        kubernetes_ansible_inventory_group: custom_cluster_1
      debian12-worker-10:
        kubernetes_is_control_plane: false
        kubernetes_ansible_inventory_group: custom_cluster_1

verifier:
  name: ansible
